"""Render committed WCSI JSON vectors as a deterministic C header."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


def _identifier(name: str) -> str:
    identifier = re.sub(r"[^A-Za-z0-9]+", "_", name).strip("_").upper()
    if not identifier or identifier[0].isdigit():
        raise ValueError(f"invalid vector name: {name!r}")
    return identifier


def render(vectors: list[dict[str, object]]) -> str:
    lines = [
        "/* Generated by tools/generate_wcsi_c_vectors.py; do not edit. */",
        "#pragma once",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
    ]
    seen: set[str] = set()
    for vector in vectors:
        name = _identifier(str(vector["name"]))
        if name in seen:
            raise ValueError(f"duplicate vector name: {name}")
        seen.add(name)
        encoded = bytes.fromhex(str(vector["encoded_hex"]))
        if not encoded:
            raise ValueError(f"empty vector: {name}")
        lines.append(f"static const uint8_t WCSI_VECTOR_{name}[] = {{")
        for offset in range(0, len(encoded), 12):
            chunk = encoded[offset : offset + 12]
            lines.append("    " + ", ".join(f"0x{byte:02x}" for byte in chunk) + ",")
        lines.extend(
            [
                "};",
                f"static const size_t WCSI_VECTOR_{name}_LEN = sizeof(WCSI_VECTOR_{name});",
                "",
            ]
        )
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args(argv)

    vectors = json.loads(args.input.read_text(encoding="utf-8"))
    if not isinstance(vectors, list):
        raise ValueError("vector document must be a JSON array")
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render(vectors), encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
